# Generated by Django 3.1.3 on 2024-01-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='localfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=149)),
                ('email', models.CharField(max_length=149)),
                ('name', models.CharField(max_length=149)),
                ('remail', models.CharField(max_length=149)),
                ('title', models.CharField(max_length=449)),
                ('file', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='files',
            name='email',
        ),
        migrations.RemoveField(
            model_name='files',
            name='name',
        ),
        migrations.RemoveField(
            model_name='files',
            name='remail',
        ),
    ]
