# Generated by Django 3.1.3 on 2024-01-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20240123_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localfiles',
            name='email',
        ),
        migrations.RemoveField(
            model_name='localfiles',
            name='name',
        ),
    ]
