# Generated by Django 3.1.3 on 2024-03-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20240123_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='recipient_email',
            field=models.CharField(default='', max_length=249),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='sender_email',
            field=models.CharField(default='', max_length=249),
            preserve_default=False,
        ),
    ]
